In [1]:
# Exercise 1: import numpy package as np

In [2]:
import numpy as np

In [3]:
# Exercise 2: Print the numpy version and the configuration 

In [4]:
print(np.__version__)
print(np.show_config())

2.4.4
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.13.8/lib/python3.13/site-packages/scipy_openblas64/include",
      "lib directory": "/opt/_internal/cpython-3.13.8/lib/pyt

/csehome/m25csa019/miniconda3/lib/python3.13/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [5]:
# Exercise 3: Create an array of 10 zeros and 20 ones

In [6]:
arr = np.zeros(10)
arr
# providing larger tensor we need to provide it in bracket, since only first parameter is shape , rest is other data typed
arr = np.zeros((10,10))
print(arr)
print(arr.shape)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(10, 10)


In [7]:
ones_arr = np.ones((20))
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [8]:
# Exercise 4: Create a vector with values ranging from 10 to 49

In [9]:
# vector = np.arrange(10,50,1)
x = list(range(10,49))
x

x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
# Exercise 5: Reverse a vector 

In [11]:
rev = x[::-1]
rev



array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [12]:
# Exercise 6: Find the indices of the non zero elements from [1, 2, 0, 0, 4, 0]

In [13]:
arr = np.array([1,2,0,0,4,0])
print(arr.shape)
print(np.nonzero(arr))
print([arr[i] for i in np.nonzero(arr)])

(6,)
(array([0, 1, 4]),)
[array([1, 2, 4])]


In [14]:
# Exercise 7: Create a 3x3 Identity matrix

In [15]:
iden = np.eye(3,3)

In [16]:
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Exercise 7.1: Generate a random number between 0 and 1 using numpy

In [18]:
rand = np.random.rand()
rand

0.7461656283302809

In [19]:
# Exercise 8: Create a 10x10 array with random values, find the minimum and maximum values

In [25]:
arr = np.random.random((10,10))
# denoising model, we do random addition of noise of that particular image size
# noise is basically blurry type
print(arr)
print(arr.min(), arr.max())
# numpy datatype arr is

[[0.95713946 0.53775044 0.27802361 0.69009313 0.91159357 0.27834328
  0.24315408 0.96612717 0.86405744 0.95723928]
 [0.10508104 0.76052001 0.17920952 0.62247597 0.29366882 0.13379034
  0.44780109 0.75266698 0.62033586 0.6609781 ]
 [0.03284933 0.58858438 0.83458627 0.40697349 0.67323477 0.99409417
  0.14031764 0.42057719 0.31605772 0.96094392]
 [0.65948073 0.59536525 0.53899841 0.98957446 0.53638486 0.44462276
  0.0417578  0.03494286 0.09409432 0.49639061]
 [0.25936035 0.12969522 0.37834137 0.23718699 0.78592717 0.00111988
  0.38889851 0.21048695 0.6940824  0.57691118]
 [0.74962841 0.98675303 0.28648383 0.31588642 0.34925354 0.31393534
  0.47093431 0.05858832 0.96570238 0.54369095]
 [0.09339891 0.05277185 0.67875053 0.58510099 0.07423562 0.03486126
  0.23582851 0.27325262 0.38483413 0.48677869]
 [0.86202274 0.99976634 0.13733085 0.05703354 0.21726161 0.93375956
  0.46984004 0.8027286  0.549874   0.7257691 ]
 [0.05636679 0.98473607 0.0618693  0.74495942 0.5906604  0.26229804
  0.68741501

In [21]:
arr = np.random.randint(0,5 ,(5,5))
arr

array([[4, 3, 3, 4, 0],
       [4, 3, 0, 4, 4],
       [4, 3, 3, 4, 4],
       [4, 0, 1, 4, 1],
       [3, 0, 1, 1, 3]])

In [22]:
# Excercise 9: Create a numpy array from the given List

In [28]:
x = [10,20,40]
print(len(x))
x = np.array(x)
print(len(x), x.shape)
# len will always give the first dimension


3
3 (3,)


In [38]:
# Exercise 10: Matrix multiplication for 1 D array
a = np.array([9, 5, 7, 4])
b =  np.array([9, 5, 4, 3])
prod = np.dot(a,b)
print(prod)
# dot product give scalar value
# np.matmul() -> need to be used when we dont have same no. of rows and column

146


In [39]:
# Exercise 11: Transpose of the given array [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]


In [40]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
a_trans = np.transpose(a)

In [33]:
a_trans

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [34]:
# Exercise 12: Given an array A, calculate the square root of the elements in it

In [35]:
A = np.arange(1,20)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [47]:
A_sqrt = np.sqrt(A)
A_sqrt

(print([i.dtype for i in np.sqrt([9,16])]))

[dtype('float64'), dtype('float64')]


In [42]:
# Exercise 13: Concatenate two numpy arrays columnwise by specifying axis = 1

In [43]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])
print(c+d)

[[ 6  8]
 [10 12]]


In [45]:
print(np.concatenate((c,d)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
# Exercise 14: print the second and the third column for the given multidimensional array

In [52]:
a = np.array([[2,4,6,8,10],
              [3, 6, 9, 12, 15],
              [4, 8, 12, 16, 20]])

print(a[:,1])

[4 6 8]


In [53]:
print(a[:,2])

[ 6  9 12]


In [54]:
print(a[:,1:3])
# all rows and only column from 1(including) till 3(excluding)

[[ 4  6]
 [ 6  9]
 [ 8 12]]


In [55]:
x = [10, 20, 30, 40, 50]
print(x[:3])

[10, 20, 30]


In [ ]:
# Exercise 15: For the given multidimensional array

# 1. Calculate the mean row wise by specifying axis = 1 and column wise by specifying axis = 0
# 2. What is the average value of an array?

In [61]:
a = np.array([[2, 4,  6,   8, 10],
              [3, 6,  9,  12, 15],
              [4, 8, 12,  16, 20]])

print(np.mean(a))
a.mean(axis = 0)

9.0


array([ 3.,  6.,  9., 12., 15.])

In [58]:
print(np.mean(a,axis = 0))

[ 3.  6.  9. 12. 15.]


In [59]:
# row wise axis = 1
print(np.mean(a,axis = 1))

[ 6.  9. 12.]


In [65]:
# Exercise 16: Create an array of all the even numbers from 30 to 70
arr = np.arange(30,71,2)
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [62]:
# Exercise 17: For the given array, get the slice of the first row and print them 

In [66]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

print(a3)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [67]:
print(a3.shape)

(3, 3, 3)


In [68]:
print(a3[0])

[[10 11 12]
 [13 14 15]
 [16 17 18]]
