Numpy:
* is the fundamental package for scientific computing in python
* provide multiple dimension array objects and multiple derived object
* fast operations on array including mathematical, logical, shape manipulation, sorting, selection, I/O, basic linear algebra, basic statistical operation


Core of NumPy package is the nd array object.

NumPy is a C, which was created a wrapper for Python, this was done because python has very simple syntax

 Pandas, Matplotlib, sckitlearn are all made over NumPy library

* Numpy array size is fixed, unlike python list it won't grow
* need to be of same data type and occupy same size in memory, homogenous array, we dont use concept of referential array 
* famous libraries using NumPy in some level


Creating Numpy Arrays

In [3]:
import numpy as np

# creating numpy arry
a = np.array([1,2,3])
# want list as input
print(type(a))
# vector

ModuleNotFoundError: No module named 'numpy'

In [3]:
# this numpy array created is a one d array
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
# provide 2D list
print(b)
# matrix

[[1 2 3]
 [4 5 6]]


In [4]:
# similarly we can create a 3D numpy array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
# this is a tensor

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# we can make numpy array of the data type we want, till now we have seen by default numpy array of integer type

#dtype
np.array([1,2,3], dtype = float)


array([1., 2., 3.])

In [6]:
#dtype
np.array([1,2,3], dtype = bool)
# 0 is treated as False ,rest are considered true

array([ True,  True,  True])

In [7]:
#dtype
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

arange -> creating array

In [8]:
# want numpy array from 1 to 10
np.arange(1,11)
# 11 not included

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

reshape

In [10]:
# convert numpy array into diff shape
np.arange(1,11).reshape(5,2)
# will get 2D array : 5 rows and 2 column

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
# convert numpy array into diff shape
np.arange(1,13).reshape(4,3)
# if no. not sufficient it will show error, we will use it alot with reshape

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

np.ones and np.zeros

In [12]:
np.ones((3,4))
# provide a tuple which will tell us the shape
# maybe used to give initial weight in CNN

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# we have also option to initialize with the random no.s
np.random.random((3,4))

array([[0.31635244, 0.04503278, 0.96061489, 0.07530789],
       [0.16414024, 0.76730995, 0.22946068, 0.78752602],
       [0.57690351, 0.24015651, 0.46072559, 0.607306  ]])

linspace

In [14]:
np.linspace(-10,10,10)
# generate points in equal distance, you imagine it by putting in the line point in a 1d line

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

identity

In [15]:
# we can create identity matrix
np.identity(3)
# 3*3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [16]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
#ndim
a1.ndim
a2.ndim
a3.ndim

3

In [18]:
# shape
a1.shape
# 1d numpy array and in one direction 10 ele

(10,)

In [19]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [20]:
print(a3.shape)
a3
# made up of 2 - 2D array of shape (2,2)

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
#size
a3.size
# 8 items in this array

8

In [22]:
# itemsize
# memory mai kitna size occupied hai 
a3.itemsize

8

In [23]:
a1.itemsize
# it is by default using int64 and hence taking 8 byte storage

8

In [24]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing datatype

In [25]:
# astype
print(a3.dtype)
# let say i want to store people age, then using int64 is wasting storage
a3.astype(np.int32)
# from nowone we will check that dataset is in it coorect datatype or not

int64


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [26]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
# scalar operation

# arithmetic
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [28]:
# relational
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
a2 > 15
# doing itemwise comparision

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
# vector operation
# arithmetic 
print(a1)
print("\n")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [31]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Array Functions

In [32]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[76., 89., 41.],
       [47., 68., 66.],
       [33., 24., 52.]])

In [33]:
np.max(a1)
np.min(a1)

np.float64(24.0)

In [34]:
np.sum(a1)

np.float64(496.0)

In [35]:
# i want to find out the minimum of each row
# 0 -> column
# 1 -> row
np.max(a1, axis = 1)

array([89., 68., 52.])

Statistical Operations

In [36]:
np.mean(a1)

np.float64(55.111111111111114)

In [37]:
np.mean(a1,axis=1)

array([68.66666667, 60.33333333, 36.33333333])

In [38]:
np.median(a1,axis=1)

array([76., 66., 33.])

In [39]:
np.var(a1)

np.float64(400.0987654320988)

Dot product

In [40]:
# shape must be compatible
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

log and exponent


In [41]:
np.log(a1)

array([[4.33073334, 4.48863637, 3.71357207],
       [3.8501476 , 4.21950771, 4.18965474],
       [3.49650756, 3.17805383, 3.95124372]])

In [42]:
np.round(np.random.random((2,3))*100)

array([[10.,  1., 79.],
       [39., 96., 71.]])

Array Slicing

In [43]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [44]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# take out last element
a1[-1]

np.int64(9)

In [46]:
a1[0]

np.int64(0)

In [47]:
# positive and negative indexing
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
# we want to take out 6
a2[1,2]
# row,col

np.int64(6)

In [49]:
a2[2,3]

np.int64(11)

In [50]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [51]:
a3[1,1,1]

np.int64(7)

In [52]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1[2:5]

array([2, 3, 4])

In [54]:
a1[2:8:2]

array([2, 4, 6])

In [55]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
a2[0,:]
# pehla row and saara column

array([0, 1, 2, 3])

In [57]:
a2[:,2]

array([ 2,  6, 10])

In [58]:
a2[1:,2]

array([ 6, 10])

In [59]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

Iterating

In [60]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for i in np.nditer(a3):
    print(i)
# first convert to 1d and then prints

0
1
2
3
4
5
6
7
